apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  root
      prefix: /
      service: kotlinsample:8080
spec:
  type: LoadBalancer
  ports:
    - name: ambassador
      port: 80
      targetPort: 80
  selector:
    service: ambassador